version: '3.7'

networks:
  app-network-public:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup:

services:
  app:
    container_name: backend
    networks:
      - app-network-public
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: postgres
      DB_HOST: db
    build:
      context: ./backend
      target: builder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 4
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - app-network-public

  db:
    container_name: db
    image: postgres:13
    networks:
      - app-network-public
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init.sql